### ISSUE TITLE
Interdistance computation issues

### ISSUE THREAD

**Issue by lmunoz79** [akoyabio/phenoptr#13]
Hi
Sorry if this is a very basic question as I'm quite new to R programming.
I'm following your guide at https://akoyabio.github.io/phenoptr/articles/computing_distances.html
and when I get to the step of "Visualizing nearest neighbours", I get an error of :**`by` can't contain join column `Cell ID CK+` which is missing from LHS**. 
I got this issue on my data (using the appropriate Cell ID <phenotype>) and using the sample_cell_seg_data, and I get the same error appropriate to the relevant phenotype.

I've copy+pasted the code as is so I don't think it's an issue of a missing value, however I noticed that the "glimpse(distances)" function on my computer only returned 4 variables on the sample_cell_seg_data, (as opposed to the 8 in the example shown in the webpage). Specifically, no "Cell ID CK+`  <int>"  type values were being produced either using the sample_cell_seg_data or my own data. 
Do you know where the issue may lie? I'm using RStudio Version 1.2.1335, R version 3.6.1 and phenoptr version 0.1.1.9007

**Comment by AB-Kent** [comment]
Please update to the latest version of `phenoptr`. The version you are using is over a year old and there have been many changes since then. Specifically, the `Cell ID` columns were added to the output of `find_nearest_distance` in [version 0.2.0](https://akoyabio.github.io/phenoptr/news/index.html#phenoptr-020).

You may also be interested in [`phenoptrReports`](https://akoyabio.github.io/phenoptrReports/index.html) which provides GUI front-ends to many `phenoptr` functions, giving access to `phenoptr` functionality without the need to program in R.

**Comment by lmunoz79** [comment]
Thanks
