### ISSUE TITLE
I think you want an na.rm = TRUE

### ISSUE THREAD

**Issue by mknafl-mda** [akoyabio/phenoptr#15]
I run into an issue with a dataset where select_rows returns only FALSE and NA.  This leads to a problem in this line, which appears to occur four times in the code.
if (sum(phenotype_cells)>0) {
This code occurs in the nearest neighbor and counts within functions.  I am a little confused how I get only false and NA when I remove phenotypes that have no occurrence in the densities produced.  
After I change the code to 
if (sum(phenotype_cells, na.rm = TRUE)>0) {
all is well.  Thanks!

**Comment by AB-Kent** [comment]
Thanks, for the report. I think a better fix for this is for `select_rows` to return `FALSE` instead of `NA`. I made this change in 385790b6. You can try it out with  
`remotes::install_github('akoyabio/phenoptr@9000')`
`remotes::install_github('akoyabio/phenoptrReports@9000') # If you are using phenoptrReports, keep them in sync`

**Comment by mknafl-mda** [comment]
Thanks Kent!  One clarification, is this change merged into the current master branch?

**Comment by AB-Kent** [comment]
No, it is on the 9000 branch. See above for installation instructions.
