### ISSUE TITLE
Issue with phenoptr: multi-radii spatial analysis error/namespace

### ISSUE THREAD

**Issue by Athanasios72** [akoyabio/phenoptr#5]
Hi,
I installed the newest version of R (3.5.3) and RStudio (1.2.1335). I also installed the latest version of "phenoptr" and run my usual script for multi-radii spatial analysis of my samples (obtained using Inform 2.3):
> library(phenoptr)
> base_path <- '~/OPAL R ANALYSIS/Mac panel/SPATIAL ANALYSIS/MULTI-RADII/IMminGC/'
> pairs <- list(
+   c('AE1AE3', 'CD68CD163'),
+   c('AE1AE3', 'CD68CD163CD206'),
+   c('AE1AE3', 'CD68CD163CD206IRF8'),
+   c('AE1AE3', 'CD68CD163IRF8'))
> radius<-c(10, 20, 30 ,40)
> counts <- count_within_batch(base_path, pairs, radius, verbose=FALSE)
Loading required namespace: rtree
Failed with error:  ‘there is no package called ‘rtree’’

Am I doing something wrong? What can I do to solve this error and run my script?
Previously I had been running R v3.3.1 and the same script run perfectly.

Thank you.

**Comment by gadenbuie** [comment]
`rtree` is a [suggested dependency](https://github.com/akoyabio/phenoptr/blob/e5e3093ad89c42bfb5b7f25cea2b738623b04571/DESCRIPTION#L34-L39) of `phenoptr`, meaning that is not installed if you used the default installation via `remotes::install_github()`. You can either install `rtree` with

```r
install.packages("rtree")
```

or you can re-install `phenoptr` with all dependencies, including those listed in _Suggests_, with

```r
remotes::install_github("akoyabio/phenoptr", dependencies = TRUE)
```

You may also need to add `force = TRUE` if `install_github()` says that the package hasn't updated since last install.

**Comment by AB-Kent** [comment]
Despite the scary message, I think your script has run correctly. Can you check if you got the expected results?

Options:
- Re-install `phenoptr` - I just pushed a change that removes this message (which is really an informational warning).
- Install `rtree` as @gadenbuie suggests; when it is installed, `count_within_batch` is much faster.
- Set `options(use.rtree.if.available=FALSE)` which will entirely restore the old behavior which does not check for or use `rtree`.

**Comment by Athanasios72** [comment]
Thank you @gadenbuie for your suggestion. I did as you suggested (reinstall with all dependencies) and my script run perfectly.
Also thank you @AB-Kent. After reinstalling with all dependencies, count_within_batch is much faster.
